### ISSUE TITLE
MapMyRun data

### ISSUE THREAD

**Issue by asperagus** [bunburya/fitness_tracker_data_parsing#1]
Hi,
I get the feeling this is trivial but I'm only learning how to use lxml and can't seem to fix it. The script works fine for MapMyRun data until it tries to parse DistanceMeters, as far as I can see this should be treated the same as the other Trackpoint data but it just returns NaN in this column. DistanceMeters doesn't seem to be recognized by find().
[truncated.zip](https://github.com/bunburya/fitness_tracker_data_parsing/files/7087125/truncated.zip)
I've attached a cut down MapMyRun .tcx file that shows this behaviour.
Thanks,
Asper

**Comment by stuartclothier** [comment]
@asperagus, I'm not sure if it is what you are asking but if you are trying to parse DistanceMeters into the points dataframe it won't work for two reasons.

1. Only trackpoints with a Position child node will be added to the points df.
2.  DistanceMeters nodes are not parsed/stored in the points df; only the laps df.

Otherwise distance seems to be parsed correctly into the laps df.

**Comment by bunburya** [comment]
@asperagus, I think stuartclothier's response is correct and what you are looking for so I will close the issue but please let me know if you still think there is an issue with the code. Thanks both!
